"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { BUSINESS } from "./business";
import { documentTotals, formatMoney } from "./calc";
import type { Customer, Invoice, LineItem, Quotation, Receipt } from "./types";

const INK = "#14181c";
const RUST = "#c1531f";
const STEEL = "#4b5a63";

function header(doc: jsPDF, docTypeLabel: string, docNumber: string, date: string) {
  doc.setFillColor(INK);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(BUSINESS.name.toUpperCase(), 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${BUSINESS.whatsappDisplay}  |  ${BUSINESS.phoneDisplay}  |  ${BUSINESS.email}`, 14, 21);

  doc.setTextColor(RUST);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(docTypeLabel.toUpperCase(), 196, 14, { align: "right" });
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`No: ${docNumber}`, 196, 20, { align: "right" });
  doc.text(`Date: ${date}`, 196, 25, { align: "right" });

  doc.setTextColor(INK);
}

function partyBlock(doc: jsPDF, customer: Customer | undefined, projectLine: string) {
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Prepared for", 14, 40);
  doc.setFont("helvetica", "normal");
  doc.text(customer?.name || "Customer", 14, 46);
  if (customer?.phone) doc.text(customer.phone, 14, 51);
  if (customer?.email) doc.text(customer.email, 14, 56);
  if (customer?.address) doc.text(customer.address, 14, 61);

  doc.setFont("helvetica", "bold");
  doc.text("Project", 120, 40);
  doc.setFont("helvetica", "normal");
  const split = doc.splitTextToSize(projectLine, 76);
  doc.text(split, 120, 46);
}

function itemsTable(doc: jsPDF, items: LineItem[], startY: number) {
  autoTable(doc, {
    startY,
    head: [["Item", "Description", "Unit", "Qty", "Unit Price", "Total"]],
    body: items.map((i, idx) => [
      String(idx + 1),
      i.description,
      i.unit,
      String(i.quantity),
      formatMoney(i.unitPrice),
      formatMoney(i.quantity * i.unitPrice),
    ]),
    headStyles: { fillColor: INK, textColor: "#ffffff", fontStyle: "bold" },
    styles: { fontSize: 9, textColor: INK, lineColor: "#d8d5cc" },
    columnStyles: { 3: { halign: "right" }, 4: { halign: "right" }, 5: { halign: "right" } },
    theme: "grid",
  });
  // @ts-expect-error - autoTable augments doc at runtime
  return doc.lastAutoTable.finalY as number;
}

function totalsBlock(
  doc: jsPDF,
  y: number,
  totals: { subtotal: number; discount: number; tax: number; otherCharges: number; grandTotal: number },
  extraRows: { label: string; value: string }[] = []
) {
  const rows: [string, string][] = [
    ["Subtotal", formatMoney(totals.subtotal)],
    ["Discount", `- ${formatMoney(totals.discount)}`],
    ["Tax", formatMoney(totals.tax)],
    ["Other charges", formatMoney(totals.otherCharges)],
  ];
  extraRows.forEach((r) => rows.push([r.label, r.value]));

  let curY = y + 8;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  rows.forEach(([label, value]) => {
    doc.text(label, 140, curY);
    doc.text(value, 196, curY, { align: "right" });
    curY += 6;
  });
  doc.setDrawColor(STEEL);
  doc.line(140, curY - 2, 196, curY - 2);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Grand Total", 140, curY + 5);
  doc.text(formatMoney(totals.grandTotal), 196, curY + 5, { align: "right" });
  return curY + 5;
}

function footer(doc: jsPDF, note?: string) {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(STEEL);
  if (note) doc.text(note, 14, pageHeight - 18);
  doc.text(
    "This document was generated by H S Constructions and is valid only with an authorized signature/stamp where required.",
    14,
    pageHeight - 12
  );
}

export function downloadQuotationPdf(quotation: Quotation, customer: Customer | undefined) {
  const doc = new jsPDF();
  header(doc, "Quotation", quotation.number, quotation.date);
  partyBlock(doc, customer, `${quotation.projectName}${quotation.projectLocation ? " — " + quotation.projectLocation : ""}`);
  const y = itemsTable(doc, quotation.items, 70);
  const totals = documentTotals(quotation.items, quotation.discount, quotation.taxPercent, quotation.otherCharges);
  totalsBlock(doc, y, totals, [
    { label: "Validity", value: `${quotation.validityDays} days from date of issue` },
  ]);
  footer(doc, quotation.notes);
  doc.save(`${quotation.number}.pdf`);
}

export function downloadInvoicePdf(invoice: Invoice, customer: Customer | undefined) {
  const doc = new jsPDF();
  header(doc, "Invoice", invoice.number, invoice.date);
  partyBlock(doc, customer, invoice.projectName);
  const y = itemsTable(doc, invoice.items, 70);
  const totals = documentTotals(invoice.items, invoice.discount, invoice.taxPercent, 0);
  const balance = totals.grandTotal - invoice.amountPaid;
  totalsBlock(doc, y, totals, [
    { label: "Amount paid", value: formatMoney(invoice.amountPaid) },
    { label: "Balance due", value: formatMoney(balance) },
  ]);
  footer(doc, invoice.paymentTerms || invoice.notes);
  doc.save(`${invoice.number}.pdf`);
}

export function downloadReceiptPdf(receipt: Receipt, customer: Customer | undefined) {
  const doc = new jsPDF();
  header(doc, "Receipt", receipt.number, receipt.date);
  partyBlock(doc, customer, receipt.projectName || "—");
  doc.setFontSize(10);
  let y = 75;
  const rows: [string, string][] = [
    ["Amount received", formatMoney(receipt.amountReceived)],
    ["Payment method", receipt.paymentMethod],
    ["Reference", receipt.reference || "—"],
    ["Remaining balance", receipt.remainingBalance != null ? formatMoney(receipt.remainingBalance) : "—"],
  ];
  rows.forEach(([label, value]) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, 80, y);
    y += 7;
  });
  footer(doc, receipt.description);
  doc.save(`${receipt.number}.pdf`);
}
